### ISSUE TITLE
Forking Sogo

### ISSUE THREAD

**Issue by mattronix** [YunoHost-Apps/z-push_ynh#13]
Hi, 

Is it ok if i fork this and tweek it a little for Sogo and add it back with a new option that allows the user to choose sogo or baikal as an option?

here is the sogo installer i made if you wanna play with it https://github.com/mattronix/sogo_ynh

**Comment by mattronix** [comment]
i was thinking to set the carddav and caldav variables based on what the users says with a few if statements.

**Comment by polytan02** [comment]
This can be considered as long as z-push agrees with it :)

Have you managed to make it work ?

**Comment by mattronix** [comment]
Yes it works :) i had some issues with my phone battery, i have not had time to update my apps for yuohost 2.0 yet tho :( .
