### ISSUE TITLE
is $path used at all ?

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost-Apps/z-push_ynh#15]
I get the impression that the install script do not use $path at all ; could you confirm that @abeudin ?

**Comment by isAAAc** [comment]
trouble during install looks like your issue, don't it ?
```
# yunohost app install https://github.com/YunoHost-Apps/z-push_ynh
Choisissez un domaine pour Z-push : mydomain.org
Attention : Impossible d'installer l'application à cet emplacement
Erreur : Échec de l'installation

```

**Comment by JocelynDelalande** [comment]
@isAAAC , this app seems, by design, to be able only to install itself at the root of a domain (thus, failing if there is another app on the same domain). @abeudin, do you confirm ?

**Comment by polytan02** [comment]
Yes, as far as I understand, it is how Microsoft defined the ActiveSync protocol.

The address has to be domain.com/Microsoft-Server-ActiveSync/

(I use this app all the time, the sources are there : https://github.com/fmbiete/Z-Push-contrib )

**Comment by isAAAc** [comment]
On 28/06/2016 15:12, polytan02 wrote:
>
> Yes, as far as I understand, it is how Microsoft defined the 
> ActiveSync protocol.
>
> The address has to be domain.com/Microsoft-Server-ActiveSync/
>
> (I use this app all the time, the sources are there : 
> https://github.com/fmbiete/Z-Push-contrib )
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/YunoHost-Apps/z-push_ynh/issues/15#issuecomment-229044268>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ABlftzHxr5vmETtUakGSbdr46wgrfZctks5qQR2kgaJpZM4I0UBN>.
>
thx, not sure it is what i search for :/


isAAAc

**Comment by fabienVM** [comment]
I have the same problem, and I have no app installed at root of the domain 

I leave here my log  :  
Command : 
yunohost app install https://github.com/YunoHost-Apps/z-push_ynh --verbose --debug

log : 

209  DEBUG loading actions map namespace 'yunohost'
230  DEBUG extra parameter classes loaded: ['ask', 'password', 'required', 'pattern']
232  DEBUG initializing base actions map parser for cli
238  DEBUG registering new callback action 'yunohost.utils.packages.ynh_packages_version' to ['-v', '--version']
551  DEBUG initialize authenticator 'ldap-anonymous' with: uri='ldap://localhost:389', base_dn='dc=yunohost,dc=org', user_rdn='None'
558  DEBUG lock has been acquired
678  INFO processing action [32313.1]: yunohost.app.install with args={'app': 'https://github.com/YunoHost-Apps/z-push_ynh', 'args': None, 'auth': <moulinette.authenticators.ldap.Authenticator object at 0xb69f44ac>, 'label': None}
692  INFO Téléchargement...
2706 INFO Extraction...
2970 INFO Terminé.
3705 INFO Vérification des paquets requis...
Choisissez un domaine pour Z-push : fabienphoto.eu
11363 INFO Exécution de la commande « sudo -n -u admin -H sh -c YNH_APP_INSTANCE_NUMBER=1 YNH_APP_ID=z-push YNH_APP_INSTANCE_NAME=z-push YNH_APP_ARG_DOMAIN=fabienphoto.eu BASH_XTRACEFD=7 /bin/bash -x "./install" fabienphoto.eu z-push 7>&1 »...
11541 INFO + domain=fabienphoto.eu
11544 INFO + path=
11548 INFO + app=z-push
11549 INFO + sudo yunohost app checkurl fabienphoto.eu -a z-push
12800 WARNING Impossible d'installer l'application à cet emplacement
12880 INFO + [[ ! 1 -eq 0 ]]
12881 INFO + exit 1
12930 INFO Exécution de la commande « sudo -n -u admin -H sh -c YNH_APP_INSTANCE_NUMBER=1 YNH_APP_ID=z-push YNH_APP_INSTANCE_NAME=z-push BASH_XTRACEFD=7 /bin/bash -x "./remove" z-push 7>&1 »...
13106 INFO + app=z-push
13111 INFO ++ sudo yunohost app setting z-push domain
13997 INFO + domain=
13998 INFO + sudo rm -rf /var/www/z-push
14107 INFO + sudo rm -rf /var/log/z-push
14215 INFO + sudo rm -f /etc/nginx/conf.d/.d/z-push.conf
14319 INFO + sudo rm -f /etc/php5/fpm/pool.d/z-push.conf
14426 INFO + sudo service php5-fpm reload
14640 INFO + sudo service nginx reload
15331 INFO + sudo yunohost app ssowatconf
17435 INFO Configuration de SSOwat générée avec succès
17672 DEBUG action [32313.1] ended after 16.992s
17674 DEBUG lock has been released
17675 ERROR Échec de l'installation

For my conclusion , the variable $YNH_APP_ARG_PATH isn't define when install script is launched, so path can't be set. 
May be we should use path="Microsoft-Server-ActiveSync/" on install script

I try with these fork : https://github.com/fabienVM/z-push_ynh and works for me.

**Comment by polytan02** [comment]
This issue should be solved with latest update.

**Comment by JocelynDelalande** [comment]
(no longer using, won't test but thanks @polytan02  :-))
