### ISSUE TITLE
Calendar don't show evens from baikal

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/z-push_ynh#17]
The calendar shows successful synchronization, but the calendar events are not displayed in calendar(calendar is empty).
The E-mail and contacts are working fine.
```


/var/www/z-push/backend/caldav/caldav.php:230 Use of undefined constant CALDAV_MAX_SYNC_PERIOD - assumed 'CALDAV_MAX_SYNC_PERIOD' (8)
03/11/2016 04:50:02 [21816] [WARN] [admin] /var/www/z-push/backend/caldav/caldav.php:230 gmdate() expects parameter 2 to be long, string given (2)
03/11/2016 04:50:02 [21816] [INFO] [admin] ExportChangesDiff->InitializeExporter(): Found '0' changes for 'Cdefault'
03/11/2016  [20919] [INFO] [admin] Version='SVN-trunk-r1981' method='POST' from='XXXXX' cmd='Sync' getUser='xxxxx.xx\admin' devId='androidc1075105823' devType='Android'
03/11/2016  [20919] [WARN] [admin] /var/www/z-push/backend/caldav/caldav.php:230 Use of undefined constant CALDAV_MAX_SYNC_PERIOD - assumed 'CALDAV_MAX_SYNC_PERIOD' (8)
03/11/2016  [20919] [WARN] [admin] /var/www/z-push/backend/caldav/caldav.php:230 gmdate() expects parameter 2 to be long, string given (2)
03/11/2016  [20919] [INFO] [admin] ExportChangesDiff->InitializeExporter(): Found '0' changes for 'Cdefault'
03/11/2016  [20920] [INFO] [admin] Version='SVN-trunk-r1981' method='POST' from='xxxxxxxxx' cmd='Sync' getUser='xxxxxx\admin' devId='androidc1075105823' devType='Android'
03/11/2016  [20920] [WARN] [admin] /var/www/z-pus
```

**Comment by meLIanTQ** [comment]
Dans un shell
nano /var/www/z-push/backend/caldav/config.php

En fin de fichier mettre:

define('CALDAV_MAX_SYNC_PERIOD', 2147483647);

**Comment by polytan02** [comment]
Just a test : if you add an event in your calendar, after the z-push sync, are the other ones appearing ?

**Comment by meLIanTQ** [comment]
Yes :)

**Comment by polytan02** [comment]
Ok. So is the problem solved if the issue is there only for the 1st sync ?

**Comment by meLIanTQ** [comment]
The first sync is working for me but not after little time. install on a fresh server with no mail or event/contacts
and iPhone ;)

**Comment by anmol26s** [comment]
I still don't see calendar. I will do more tests.

Testing device nokia N8
logs: 
07/02/2017 22:20:30 [25178] [INFO] [user] ExportChangesDiff->InitializeExporter(): Found '0' changes for 'Tdefault'
07/02/2017 22:20:31 [25183] [INFO] [user] Version='SVN-trunk-r1981' method='POST' from='XXXXXXXXX' cmd='Sync' getUser='user' devId='imeiXXXXXXXXXXXX' devType='XXXXXX'
07/02/2017 22:20:32 [25183] [INFO] [user] NoHierarchyCacheAvailableException: Folderid 'i/0005ad5d' is not fully synchronized on the device - code: 0 - file: /var/www/z-push/lib/core/devicemanager.php:397
07/02/2017 22:20:32 [25183] [INFO] [userl] Full device resync requested
07/02/2017 22:20:32 [25183] [WARN] [user] Not possible to determine class of request. Request did not contain class and apparently there is an issue with the HierarchyCache.
07/02/2017 22:20:33 [24407] [INFO] [user] Version='SVN-trunk-r1981' method='POST' from='117.XXX.XXXX.XX' cmd='Sync' getUser='user' devId='imeiXXXXXXXXXX' devType='XXXXl'
07/02/2017 22:20:34 [24407] [INFO] [user] NoHierarchyCacheAvailableException: Folderid 'i/237a6179' is not fully synchronized on the device - code: 0 - file: /var/www/z-push/lib/core/devicemanager.php:397
07/02/2017 22:20:34 [24407] [INFO] [user] Full device resync requested
07/02/2017 22:20:34 [24407] [WARN] [user] Not possible to determine class of request. Request did not contain class and apparently there is an issue with the HierarchyCache.

**Comment by polytan02** [comment]
The calendar/contacts sync has always been weird with z-push.
There is another rep, but not sure if it will work better....

**Comment by polytan02** [comment]
I have push a basic update to download sources from the github of https://github.com/fmbiete/Z-Push-contrib/ instead of having them in the app directly.

Now, I can fork this to try another set of sources, directly from http://z-push.org/  and its git : https://stash.z-hub.io/projects/ZP/repos/z-push/browse

Would you be keen to try if it works fine ?

**Comment by anmol26s** [comment]
Do you want me to update it, then test it?

**Comment by polytan02** [comment]
I need to fork and configure the app to use the new sources. I will try to do it tonight and let you know :) @anmol26s @meLIanTQ

**Comment by anmol26s** [comment]
@polytan02 ok

**Comment by meLIanTQ** [comment]
ok

**Comment by polytan02** [comment]
Et voila, it should be ready : 
https://github.com/polytan02/z-push_ynh

For those ready to try, please could you remove your current z-push and install this one ?

Also, I would be grateful if you could open issues in my fork so as not to mix things. 

Test and feedback ! :)

**Comment by polytan02** [comment]
The tests I have done with the latest sources looks quite promising @fbartels @anmol26s @meLIanTQ !
I can send/receive emails, add meeting invitation and send the invit to other, they can accept and I see it and also I don't have problem for contacts sync.

https://github.com/polytan02/z-push_ynh

If you believe this is good too, then we can merge the fork into the official ynh depot.

**Comment by anmol26s** [comment]
I removed the old z-push and installed your repo. But after the install the baikal crashed.It gives 403 Forbidden error. I removed your z-push repo, agendav and baikal. Then did a fresh install of baikal but I am still getting 403 Forbidden error. :(

**Comment by anmol26s** [comment]
Opened a ticket on forum [https://forum.yunohost.org/t/urgent-baikal-inaccessible-403-forbidden/2471](https://forum.yunohost.org/t/urgent-baikal-inaccessible-403-forbidden/2471)

**Comment by anmol26s** [comment]
I have solved the issue from the ticket, but can you check it the solution in the ticket is safe for the permission ?
Installing your z-push repo and testing it :)

**Comment by polytan02** [comment]
Hi @anmol26s , z-push should have no impact on your baikal setup :) 

Many thanks for testing, let us know if it works well !
