### ISSUE TITLE
Upgrade to latest Z-Push and official package repository

### ISSUE THREAD

**Issue by fbartels** [YunoHost-Apps/z-push_ynh#18]
Hi,

Z-Push 2.3 (which was released last august) now features official packages and a package repository, which should make it much easier to keep up to date.

If you need any help updating this app let me know.

**Comment by polytan02** [comment]
I'm working on that in https://github.com/polytan02/z-push_ynh as it requires quite some work to redo all the config files.

**Comment by fbartels** [comment]
@polytan02 great, good to know. I would really suggest to go for the package repositories instead of the source archive.

You can find more information about the packages and repository at https://wiki.z-hub.io/display/ZP/Installation#Installation-DebianundUbuntubasedsystems

**Comment by polytan02** [comment]
I thought about using the debian package but as we need to modify quite a few config files, I am concerned of "automatic" update. I would rather prefer updating z-push sources only when we update the ynh app (so we can test, etc)

**Comment by fbartels** [comment]
I've had a short look at the app and as long as you don't auto replace config files on update you should actually be fine. But I can totally understand the "better safe than sorry" approach.

**Comment by polytan02** [comment]
Thanks :) 

I will try to finish the fork this weekend and let you know. It shouldn't be too long, just takes time.

**Comment by polytan02** [comment]
@fbartels I have done a fork to test the latest sources : 

https://github.com/polytan02/z-push_ynh

Please test and comment ! For issues related to z-push 2.3, please open tickets in the forked depot.

The aim is to merge eventually.

**Comment by fbartels** [comment]
I am not a Yunohost user so I cannot much comment on how well it works with their system (I am rather one of the Z-Push contributors and came by this repository), but I can confirm that it installs and I am able to connect a testing device.

I came across some things that I would say are a bit odd:
https://github.com/polytan02/z-push_ynh/blob/master/conf/config.php#L64 - by default this is /var/lib/z-push, on my test system this was set to /var/www/z-push/. The important part here is that the webserver has read/write permissions on that folder, but it does not really have to be exposed to the outside world by the webserver (I would actually not really recommend to do so). I would recommend to set this to /var/lib/z-push.

You man want to include logrotation for the files in /var/log/z-push as very large logfiles can slow down your webserver/synchronisation. You can find an example at https://stash.z-hub.io/projects/ZP/repos/z-push/browse/config/z-push.lr. As it seems you can directly reuse it, as the webserver on yunohost seems to be running as www-data as well.

**Comment by polytan02** [comment]
@fbartels Many thanks for your comments.
- I will look into STATE_DIR : is it data we need to keep in between updates of z-push ? At this stage when we upgrade we remove all content of /var/www/z-push so we loss them. I could put them in /home/yunohost.app/z-push for example
- I have notice some "resync" functions in the documentation of z-push https://wiki.z-hub.io/display/ZP/Upgrade+to+Z-Push+2.3
- Definitely, I will look into logrotate


One thing you could help is the imap backend config ? For example, I am really not sure of https://github.com/polytan02/z-push_ynh/blob/master/conf/backend/config-imap.php#L140 With yunohost, we could have a user define as such : 
- username : john
- First name : John
- family name : Doe
- email address : john.doe@domain.tld

For the LDAP part I put https://github.com/polytan02/z-push_ynh/blob/master/conf/backend/config-imap.php#L165 but again, this may only be a lucky guess.

**Comment by fbartels** [comment]
Yes, the state dir should definitely be kept, since once the state has been removed all connected devices will resync. (which on the other hand means that you don't have to care that much about https://wiki.z-hub.io/display/ZP/Upgrade+to+Z-Push+2.3).

I actually have not clue about https://github.com/polytan02/z-push_ynh/blob/master/conf/backend/config-imap.php#L140 and https://github.com/polytan02/z-push_ynh/blob/master/conf/backend/config-imap.php#L165, but looking at the config file it seems these are meant to replace user information (when also a mysql or ldap host is given with credentials). So I would not worry about this if you did not have that in before.

**Comment by polytan02** [comment]
@fbartels I have added logrotate capability in the fork  https://github.com/polytan02/z-push_ynh

**Comment by polytan02** [comment]
@fbartels I have added the states files in /home/yunohost.app:$app instead of /var/www/$app

**Comment by polytan02** [comment]
You can upgrade the app by doing 
# yunohost app upgrade -u https://github.com/polytan02/z-push_ynh z-push

**Comment by fbartels** [comment]
Hi @polytan02 ,

I've left the machine with the testing office over the weekend. I'll try the updated version on monday.

**Comment by fbartels** [comment]
Ok, upgrade went fine and my previous remarks now all seem solved. While sending a testmail I noticed the following error in the z-push logging:

```
13/02/2017 09:56:46 [ 2029] [ERROR] [test] BackendIMAP->saveSentMessage(): The email could not be saved to Sent Items folder. Check your configuration.
```

But this seems do to the fact that no folder hierarchy is created in Yunohost by default (I only had the inbox, no deleted items etc).

**Comment by polytan02** [comment]
@fbartels I have had this issue for a long time, even with other sources. To sort it, I must use roundcube or rainloop to send an email, and only then z-push is able to see the "Sent" folder and so see the sent items.

Rianloop is the most obvious test : z-push only sees the "Inbox" folder, then if I connect to rainloop it creates "Sent", "Archives", etc, and only then z-push sees the other folders.

Would there be a away to configure z-push to create the missing folders for first time users ?

**Comment by polytan02** [comment]
@fbartels Oh, and I forgot : many thanks for your comments and advise, it let us go in the right direction :) I can assure you your feedback is appreciated !

**Comment by fbartels** [comment]
> I have had this issue for a long time, even with other sources.

Actually it would be better to fix it in the Yunohost Dovecot configuration directly. e.g. with 
```
namespace {
    type = private
    separator = /
    prefix =
    inbox = yes

    mailbox Sent {
        auto = subscribe
        special_use = \Sent
    }
    mailbox Drafts {
        auto = subscribe
        special_use = \Drafts
    }
    mailbox Trash {
        auto = subscribe
        special_use = \Trash
    }
    mailbox Junk {
        auto = subscribe
        special_use = \Junk
    }
}
```
Some more info in https://forum.vestacp.com/viewtopic.php?t=4809#p11499

Disclaimer there may be other ways to achieve this. This was just the first thing that Google turned up for me.

**Comment by polytan02** [comment]
@fbartels I have changed the dovecot configuration to have the auto = subscribe (I also read the dovecot documentation to understand what it should do).
It doesn't seem to do anything :/ 

Surprinsgly, when I send an email from rainloop, then straight away z-push detects the newly created folders and it all works fine.

Is the z-push function to create the folder (or make the request to create the folder) actually working ?

**Comment by fbartels** [comment]
Hi, no the snippit I posted has be be in the configuration at the time the mailbox was created. Afaik the imap backend of Z-Push has no auto create of folders (but it also not really my home turn), if you are fit in php and want to work at this a pull request is welcome. 

https://wiki.z-hub.io/display/ZP/Development+guidelines
