### ISSUE TITLE
Direct SMTP connection instead of php_mail() function

### ISSUE THREAD

**Issue by polytan02** [YunoHost-Apps/z-push_ynh#22]
@fbartels I have changed the configuration in https://github.com/polytan02/z-push_ynh imap backend to use smtp with auth instead of php_mail() function. 
This let us authenticate emails, which seems much better (it activates dkim, etc)

The config I use is as such : 
https://github.com/polytan02/z-push_ynh/commit/c39cb832bf20d7902ed81c5f3dbe97345af0f81b
`$imap_smtp_params = array('host' => 'ssl://DOMAINTOCHANGE', 'port' => 465, 'auth' => true, 'username' => 'imap_username', 'password' => 'imap_password', 'verify_peer' => true, 'verify_peer_name' => true, 'allow_self_signed' => true);`

DOMAINTOCHANGE is transformed in domain.tld

But when I do that, I get some weird ERROR codes (but the email are sent and things look good...)

> 14/02/2017 00:57:00 [ 4554] [ERROR] [ben] trace error: /var/www/z-push/backend/imap/Mail/smtp.php:280 Only variables should be assigned by reference (2048) - backtrace: 6 steps
> 14/02/2017 00:57:00 [ 4554] [ERROR] [ben] trace: 1:/var/www/z-push/backend/imap/imap.php:2459 - Mail_smtp->send()
> 14/02/2017 00:57:00 [ 4554] [ERROR] [ben] trace: 2:/var/www/z-push/backend/imap/imap.php:303 - BackendIMAP->sendMessage()
> 14/02/2017 00:57:00 [ 4554] [ERROR] [ben] trace: 3:/var/www/z-push/backend/combined/combined.php:268 - BackendIMAP->SendMail()
> 14/02/2017 00:57:00 [ 4554] [ERROR] [ben] trace: 4:/var/www/z-push/lib/request/sendmail.php:127 - BackendCombined->SendMail()
> 14/02/2017 00:57:00 [ 4554] [ERROR] [ben] trace: 5:/var/www/z-push/lib/request/requestprocessor.php:110 - SendMail->Handle()
> 14/02/2017 00:57:00 [ 4554] [ERROR] [ben] trace: 6:/var/www/z-push/index.php:107 - RequestProcessor::HandleRequest()

Would you have any idea of why it does that by any chance ?

**Comment by fbartels** [comment]
Hi,

like I said the imap backend of z-push is not really my home turf. You probably get better help at https://forum.kopano.io/category/28/z-push-when-using-other-backends (new forum) or https://forums.zarafa.com/forumdisplay.php?72-Z-Push-when-using-other-backends (old forum).

**Comment by polytan02** [comment]
Sorted using TLS and port 587
