### ISSUE TITLE
 z-push seems unable to create mailboxes folders

### ISSUE THREAD

**Issue by polytan02** [YunoHost-Apps/z-push_ynh#25]
z-push seems unable to create mailboxes folders. It means that you must send at least one email from roundcube or rainloop to have the mailboxes created. After than it all works fine.

**Comment by polytan02** [comment]
Bug opened there [https://jira.z-hub.io/browse/ZP-1184](https://jira.z-hub.io/browse/ZP-1184)

**Comment by yalh76** [comment]
upstream issue closed
