### ISSUE TITLE
Update to z-push 2.3.7

### ISSUE THREAD

**Issue by polytan02** [YunoHost-Apps/z-push_ynh#30]
http://z-push.org/z-push-2-3-7-release/

https://stash.z-hub.io/projects/ZP/repos/z-push/compare/diff?targetBranch=refs%2Ftags%2F2.3.6&sourceBranch=refs%2Ftags%2F2.3.7

**Comment by anmol26s** [comment]
Will this be updated to 2.3.9 and made compatible with YunoHost 3 ? Do you still maintain this app ?

**Comment by fbartels** [comment]
There is actually a 2.4.3 meanwhile http://z-push.org/z-push-2-4-3-final-release/

**Comment by anmol26s** [comment]
Any news on this? I have to use z-push on my old nokia n8 phone for contact sync.

**Comment by anmol26s** [comment]
up

**Comment by yalh76** [comment]
Made a PR for Z-Push 2.4.5
https://github.com/YunoHost-Apps/z-push_ynh/pull/32

**Comment by yalh76** [comment]
Master branch is now 2.4.5
