### ISSUE TITLE
problème de compte mail

### ISSUE THREAD

**Issue by ZeJMaN** [YunoHost-Apps/z-push_ynh#4]
Bonjour et merci pour le travail ! 

J'ai un problème quand j'ai un problème avec Z-PUSH sur mon serveur yunohost mes comptes mails sont formé comme cela : 
prenom.nom@domain.fr

quand j'envoi un mail depuis une machine qui passe par Z-push le mail de l'expediteur est prenom@domain.fr

j'ai l'impression que z-push utilise le nom du compte yunohost plutot que le compte mail.

J'ai essayé sur plusieur installations fraiches et j'ai toujours ce même problème. Pourtant quand j'essai avec roundcube j'ai bien la bonne addresse qui s'affiche chez mon ionterlocuteur.

Comment je peu corriger ça ?

**Comment by polytan02** [comment]
Is this problem still there with latest version of the app ?

**Comment by polytan02** [comment]
Effectivement, j'arrive à reproduire le bug. Je pense que cela vient de la config imap.php de z-push.
Je n'ai pas fais ce réglage, donc pas sur de savoir comment le résoudre, je suppose que le soucis vient de là : 
https://github.com/YunoHost-Apps/z-push_ynh/blob/master/conf/backend/config-imap.php#L158

**Comment by polytan02** [comment]
I think the bug has been sorted with latest commit : b2e6e2f2fe1a019114e92ccfdfb03f6151d4efd5
