### ISSUE TITLE
Baikal with Z-push with an android device

### ISSUE THREAD

**Issue by jongerenchaos** [YunoHost-Apps/z-push_ynh#47]
The installation of Z-push in combination with Baikal works very well. I try it on a virtual image hosting company with the standard SSL from letsencrypt. It works out of the box but there are some various problems:
- I can add various contacts and calendar events on the system with a program to read and write this to baikal.
- When i add my Android cellphone to the Z-push/baikal software it give some problems. The first synchronize try there was nothing to see in the calendar and addressbook list. But when i try it the second time it works. When i try to synchronize it again the calendar and addressbook are away again.
- When i try to add a new appointment or contact on my android smartphone it doesn't work. After synchronizing the contact and or appointment are away and it doesn't synchronize with baikal.

I try to install this 5 times on various servers and it never works... 

In the error log i get the following error message:
`20/11/2019 11:08:43 [ 1146] [WARN] [username] Mobile loop detected! Messages sent to the mobile will be restricted to 1 items in order to identify the conflict`

How can i resolve this issue?

**Comment by yalh76** [comment]
Have you tried with the last z-push version 2.5.1 ?

**Comment by yalh76** [comment]
Feel free to reopen that issue if you still have a problem.
