### ISSUE TITLE
iPhone username instead of email regression

### ISSUE THREAD

**Issue by axemann** [YunoHost-Apps/z-push_ynh#50]
Hi,

It looks like the issue that was reportedly fixed in #26 has returned in version 2.5.1~ynh2.  I'm using iOS 13.3 on an iPhone XS.

**Comment by yalh76** [comment]
I have to check that, it will took time

**Comment by yalh76** [comment]
I've tested and it still work with the email address, Maybe something specific from your configuration...

**Comment by fbartels** [comment]
There is a config option for this:

https://github.com/Z-Hub/Z-Push/blob/c67f4dce4aa4f181efda54ca936bb5539543c56b/src/config.php#L57

**Comment by yalh76** [comment]
Can you test doing: `yunohost app upgrade z-push -u https://github.com/YunoHost-Apps/z-push_ynh/tree/USE_FULLEMAIL_FOR_LOGIN` to see if it solves the issue.

**Comment by axemann** [comment]
Sorry for the delay on this.  I just tested with the above branch, and it appears to have resolved the issue.  

When setting up the account in iOS, the account no longer reverts from the email address to the username after saving the config, and I was able to send an email to an outside address with no issues from my phone.

**Comment by yalh76** [comment]
Thanks, Perfect, I will merge it
