### ISSUE TITLE
Card sync error

### ISSUE THREAD

**Issue by adrien80080** [YunoHost-Apps/z-push_ynh#7]
Hello,
if i try to sync my Baikal calendar, i have an error in /var/log/z-push/z-push.log : 
<code>27/06/2015 17:27:22 [13710] [WARN] [adrien] /var/www/z-push/include/z_caldav.php:908 Undefined index: /baikal/cal.php/calendars/adrien/perso001/ ( 8 )</code>

Bonjour,
si j'essaye de synchroniser mon calendrier Baika, j'ai une erreur dans /var/log/z-push/z-push.log : 
<code>27/06/2015 17:27:22 [13710] [WARN] [adrien] /var/www/z-push/include/z_caldav.php:908 Undefined index: /baikal/cal.php/calendars/adrien/perso001/ ( 8 )</code>

**Comment by src386** [comment]
Same here but it's working.

**Comment by polytan02** [comment]
Is this still the case with latest version ?
