### ISSUE TITLE
Suggestion: Merge with tine20/syncroton

### ISSUE THREAD

**Issue by TCB13** [YunoHost-Apps/z-push_ynh#81]
Hello,

First, let me tank you all for the continued efforts in maintain this fork of the original z-push.

I would like to suggest to @polytan02 and others that are actively contributing and developing this fork to merge the project with https://github.com/tine20/syncroton (or vice versa). Both projects are active but probably lack from contributions and the later one is working in ActiveSync v16 support.

This request also applies to @alecpl that seems to be the lead on syncroton.

Thank you all.

**Comment by yalh76** [comment]
Hi,

we are not maintaining z-push but a package of z-push for YunoHost
